version: '3'
services:
    nginx:
        container_name: nginx_dev
        image: nginx_dev
        restart: always
        build:
            context: ./
            dockerfile: ./nginx/Dockerfile
        environment:
         - VIRTUAL_HOST=developer.dev # Environment variable needed for nginx proxy
         - LETSENCRYPT_HOST=developer.dev # Environment variables needed for Let's Encrypt companion
         - LETSENCRYPT_EMAIL=jjolon@mineco.gob.gt
        expose:
         - "80" # Expose http port
         - "443" # along with https port
        networks:
         - nginx-proxy # Connect this container to network named nginx-proxy, that will be described below
    php:
        container_name: php
        image: php-frm
        expose:
            - "9000" # Expose http port
        networks:
            - nginx-proxy
        build: 
            context: ./
            dockerfile: ./php/Dockerfile
        volumes:
            - ./php-fpm/php5.6.ini:/usr/local/etc/php/php.ini
            
networks:
    nginx-proxy:
        external:
            name: proxy_nginx-proxy # Reference our network that was created by Docker Compose when we launched our two main containers earlier. Name generated automatically. Use `docker network ls` to list all networks and their names.
