<style>

/*Estilos Generales*/
.button {
background:#7f8c8d;
color:#fff;
display:inline-block;
font-size:1.25em;
margin:20px;
padding:10px 0;
text-align:center;
width:200px;
height:20px;
text-decoration:none;
box-shadow:0px 3px 0px #373c3c;
font:"Segoe UI";
}
 
.button span {
margin-right:15px;
}
 
/*Colores*/
.button.red {
background:#FF0000;
box-shadow:0px 3px 0px #266792;
font:"Segoe UI";
}
 
.button.yellow {
background:#e67e22;
box-shadow:0px 0px 0px #b55704;
}
 
 
 .button.green {
background:#00CC00;
box-shadow:0px 0px 0px #b55704;
}
 
/*Tamaños*/
.button.medium {
width:350px;
}
 
 
.button.large {
width:450px;
}
 
 
.button.radius {
border-radius:30px;
}
 
/*Efectos, Hover*/
.button:hover {
box-shadow:0px 0px 0px;
padding-top:3px;
}
</style>
<!-- menu -->
<div>
<div>Menú</div>
<hr/>
<p>
<p>
<p>
	<!-- Botones Chicos -->
	<a href="ingresoempresa/ingresoem.php" class="button red" target="central">
	<span class="icon-house"></span>No Atendidas</a>
	
	<a href="reporte/reporte.php" class="button yellow" target="central">En Proceso</a>
	
		<a href="reporte/reporte.php" class="button green" target="central">Finalizadas</a>
	

	<br>

