# FROM webimp/php-56-apache
FROM php:7.2-apache

# COPY php.ini /usr/local/etc/php

# RUN apt-get -y install unixodbc-dev
# RUN pecl install sqlsrv pdo_sqlsrv

# RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer \
#     && ln -s $(composer config --global home) /root/composer
# ENV PATH=$PATH:/root/composer/vendor/bin COMPOSER_ALLOW_SUPERUSER=1

