version: '3'

services:
    php:
        # image: webimp/php-56-apache
        # image: jtabet/php-ext-sqlsrv
        build:
            context: ./
            dockerfile: Dockerfile
        container_name: php-server
        restart: always
        ports:
         - "80:80"
        volumes: 
            - ./www:/usr/local/apache2
            # - ./www:/var/www/html
            # - ./pdo:/usr/local/lib/php/extensions/no-debug-non-zts-20131226
    
    # nginx:
    #     build: 
    #         context: ./nginx
    #         dockerfile: Dockerfile
    #     container_name: nginx
    #     restart: always
    #     depends_on: 
    #       - php
    #     expose:
    #         - "80" # Expose http port
    #         - "443" # along with https port
    #     volumes_from: 
    #         - php

volumes:
    www: {}     
