version: '3'
services:
    php:
        build:
            context: ./
            dockerfile: Dockerfile
        container_name: php-server
        restart: always
        # ports:
        #  - "8080:80"
        volumes: 
            - ./www:/var/www/html
            # - ./pdo:/usr/local/lib/php/extensions/no-debug-non-zts-20170718
    
    nginx:
        build: 
            context: ./nginx
            dockerfile: Dockerfile
        container_name: nginx
        restart: always
        depends_on: 
          - php
        ports: 
            - "8080:80"
        volumes_from: 
            - php

volumes:
    www: {}           
