version: '3'
services:
    php:
        build:
            context: ./
            dockerfile: Dockerfile
        container_name: php-server
        restart: always
        ports:
         - "8080:80"
        volumes: 
            - ./www:/var/www/html
            - ./pdo:/usr/local/lib/php/extensions/no-debug-nom-zts-20170718

volumes:
    www: {}           
