version: '3'

services:
    php:
        # image: webimp/php-56-apache
        # image: jtabet/php-ext-sqlsrv
        build:
            context: ./
            dockerfile: Dockerfile
        container_name: php-server
        restart: always
        ports:
         - "80:80"
        volumes: 
        #     - ./www:/usr/local/apache2
            # - ./www:/var/www/html
            - ./www:/www
            # - ./pdo:/usr/local/lib/php/extensions/no-debug-non-zts-20131226
    # nginx:
    #     image: wodby/nginx:1.15-5.4.0
    #     depends_on:
    #         - php
    #     environment:
    #         NGINX_STATIC_OPEN_FILE_CACHE: "off"
    #         NGINX_ERROR_LOG_LEVEL: debug
    #         NGINX_BACKEND_HOST: php
    #         NGINX_VHOST_PRESET: php
    #     volumes:
    #         - ./www:/var/www/html:cached
    #     labels:
    #         - 'traefik.backend=php_sqlsrv_example_nginx'
    #         - 'traefik.port=80'
    #         - 'traefik.frontend.rule=Host:php-sqlsrv-example.local'
    
    # nginx:
    #     build: 
    #         context: ./nginx
    #         dockerfile: Dockerfile
    #     container_name: nginx
    #     restart: always
    #     depends_on: 
    #       - php
    #     expose:
    #         - "80" # Expose http port
    #         - "443" # along with https port
    #     volumes_from: 
    #         - php

volumes:
    www: {}     
